# Generated by Django 4.2.9 on 2024-02-09 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Categories',
            new_name='categories',
        ),
    ]
